---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-api
stringData:
  mysql-password: devops123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-api
data:
  mysql-user: devops
  mysql-db: student
