# Default values for flask-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: arataem/flask-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: FLASK_APP
  value: api.py
- name: FLASK_ENV
  value: development
- name: DB_USERNAME
  valueFrom:
    configMapKeyRef:
      name: mysql-config
      key: mysql-user
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mysql-secret
      key: mysql-password
- name: DB_HOSTNAME
  value: mysql-0.mysql
- name: DB_NAME
  valueFrom:
    configMapKeyRef:
      name: mysql-config
      key: mysql-db

probes:
  startupProbe:
    httpGet:
      path: /api/health-check/ok
      port: flask
    failureThreshold: 5
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /api/health-check/ok
      port: flask
    failureThreshold: 5
    periodSeconds: 3