---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  mysql-password: devops123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-user: devops
  mysql-db: student
